// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Blockstack = require("blockstack");
var $$Storage = require("blockstack/lib/storage");

function getFileFromUser(file, username, app) {
  return $$Storage.getFile(file, {
              username: username,
              decrypt: false,
              app: app
            });
}

function getFileFromUserAndDecrypt(file, username) {
  return $$Storage.getFile(file, {
              username: username,
              decrypt: true
            });
}

function putFileEncryptedFor(path, content, pubKey) {
  return Blockstack.putFile(path, content, {
              encrypt: pubKey
            });
}

exports.getFileFromUser = getFileFromUser;
exports.getFileFromUserAndDecrypt = getFileFromUserAndDecrypt;
exports.putFileEncryptedFor = putFileEncryptedFor;
/* blockstack Not a pure module */
