// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Id = require("bs-platform/lib/js/belt_Id.js");
var Belt_Set = require("bs-platform/lib/js/belt_Set.js");
var Caml_primitive = require("bs-platform/lib/js/caml_primitive.js");

function compareUtxos(param, param$1) {
  var c = Caml_primitive.caml_string_compare(param.txId, param$1.txId);
  if (c !== 0) {
    return c;
  } else {
    return Caml_primitive.caml_int_compare(param.txOutputN, param$1.txOutputN);
  }
}

var include = Belt_Id.MakeComparableU({
      cmp: compareUtxos
    });

var cmp = include.cmp;

var UtxoCmp = {
  compareUtxos: compareUtxos,
  cmp: cmp
};

var emptyUtxoSet = Belt_Set.make({
      cmp: cmp
    });

exports.UtxoCmp = UtxoCmp;
exports.emptyUtxoSet = emptyUtxoSet;
/* include Not a pure module */
